# Generated by Django 3.0.5 on 2020-05-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaMon', models.CharField(max_length=4)),
                ('TenMon', models.TextField()),
                ('Nam', models.IntegerField(null=True)),
                ('HocKy', models.IntegerField(null=True)),
                ('GioiThieu', models.TextField(null=True)),
            ],
        ),
    ]
