# Generated by Django 3.0.5 on 2020-05-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonHoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mon',
            name='GioiThieu',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
