# Generated by Django 3.0.5 on 2020-05-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppChinh', '0001_initial'),
        ('MonHoc', '0003_auto_20200511_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baihoc',
            name='MaMon',
        ),
        migrations.AlterField(
            model_name='baihoc',
            name='NoiDung',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mon',
            name='GioiThieu',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mon',
            name='HocKy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mon',
            name='Nam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BinhLuanBH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoiDungBL', models.TextField()),
                ('NgayBL', models.DateTimeField(auto_now_add=True)),
                ('baihoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonHoc.BaiHoc')),
                ('nguoidung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppChinh.NguoiDung')),
            ],
        ),
    ]
