# Generated by Django 3.0.5 on 2020-05-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonHoc', '0004_auto_20200514_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binhluanbh',
            name='baihoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baihocbl', to='MonHoc.BaiHoc'),
        ),
    ]
