# Generated by Django 3.0.5 on 2020-05-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonHoc', '0005_auto_20200525_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mon',
            name='HocKy',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='mon',
            name='Nam',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
