# Generated by Django 3.0.5 on 2020-05-28 08:29

import MonHoc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonHoc', '0010_auto_20200526_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baihoc',
            name='NoiDung',
            field=models.FileField(blank=True, default='No file', upload_to=MonHoc.models.taoPathchoBH),
        ),
        migrations.AlterField(
            model_name='mon',
            name='GioiThieu',
            field=models.FileField(blank=True, default='No file', upload_to=MonHoc.models.taoPathchoGioiThieuMH),
        ),
    ]
