# Generated by Django 3.0.5 on 2020-08-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppChinh', '0004_ttlienhe'),
        ('MonHoc', '0011_auto_20200528_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiKiemTra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenBaiKT', models.TextField()),
                ('ThoiGianLamBai', models.IntegerField(default=60)),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonHoc.Mon')),
            ],
        ),
        migrations.CreateModel(
            name='ThanhTich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diem', models.FloatField(default=0.0)),
                ('ThoiGianBD', models.DateTimeField(blank=True)),
                ('ThoiGianKT', models.DateTimeField(blank=True)),
                ('baikiemtra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonHoc.BaiKiemTra')),
                ('nguoidung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppChinh.NguoiDung')),
            ],
        ),
    ]
