# Generated by Django 3.0.5 on 2020-08-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonHoc', '0012_baikiemtra_thanhtich'),
    ]

    operations = [
        migrations.AddField(
            model_name='baikiemtra',
            name='NoiDungBaiKT',
            field=models.FileField(default='No file', upload_to=''),
        ),
    ]
