# Generated by Django 3.0.5 on 2020-05-18 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppChinh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiThongBao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoaiTB', models.CharField(max_length=10)),
                ('AnhTB', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDeTB', models.CharField(max_length=100)),
                ('NoiDungTB', models.TextField()),
                ('NgayTB', models.DateTimeField(auto_now_add=True)),
                ('LoaiTB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppChinh.LoaiThongBao')),
            ],
        ),
    ]
