# Generated by Django 3.0.5 on 2020-05-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChinh', '0002_loaithongbao_thongbao'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='password_MaHoa',
            field=models.CharField(default='Chua ma hoa', max_length=100),
        ),
        migrations.AlterField(
            model_name='loaithongbao',
            name='AnhTB',
            field=models.ImageField(blank=True, upload_to='HinhAnh/'),
        ),
    ]
