# Generated by Django 3.0.5 on 2020-05-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChinh', '0003_auto_20200526_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTLienHe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenBanLH', models.CharField(max_length=20)),
                ('TieuDeLH', models.CharField(max_length=100)),
                ('ThongDiepLH', models.TextField()),
                ('EmailBanLH', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
